// Defines the shape of a Princess object returned by MockAPI
export interface Princess {
  id: string;          // Auto-generated by MockAPI
  name: string;        // Princess name (e.g., "Cinderella")
  movie: string;       // Film the princess is from
  imageUrl: string;    // URL to a photo of the princess
  description: string; // Short bio
  createdAt?: string;  // Auto-set by MockAPI
}
